channels:
- pytorch
- nvidia
- conda-forge
- defaults
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=5.1
- backcall=0.2.0
- blas=1.0
- brotli-python=1.0.9
- bzip2=1.0.8
- ca-certificates=2025.1.31
- certifi=2024.8.30
- charset-normalizer=3.3.2
- colorama=0.4.6
- cuda-cudart=11.7.99
- cuda-cupti=11.7.101
- cuda-libraries=11.7.1
- cuda-nvrtc=11.7.99
- cuda-nvtx=11.7.91
- cuda-runtime=11.7.1
- cuda-version=12.6
- decorator=4.4.2
- entrypoints=0.4
- ffmpeg=4.3
- filelock=3.13.1
- freetype=2.12.1
- fsspec=2024.9.0
- gmp=6.2.1
- gmpy2=2.1.2
- gnutls=3.6.15
- idna=3.7
- intel-openmp=2023.1.0
- ipykernel=5.5.5
- ipython=7.33.0
- ipython_genutils=0.2.0
- jedi=0.18.2
- jinja2=3.1.4
- jpeg=9e
- jupyter_client=7.0.6
- jupyter_core=5.7.2
- lame=3.100
- lcms2=2.12
- ld_impl_linux-64=2.40
- lerc=3.0
- libcublas=11.10.3.66
- libcufft=10.7.2.124
- libcufile=1.11.1.6
- libcurand=10.3.7.77
- libcusolver=11.4.0.1
- libcusparse=11.7.4.91
- libdeflate=1.17
- libffi=3.4.4
- libgcc-ng=11.2.0
- libgomp=11.2.0
- libiconv=1.16
- libidn2=2.3.4
- libnpp=11.7.4.75
- libnvjpeg=11.8.0.2
- libpng=1.6.39
- libsodium=1.0.18
- libstdcxx-ng=11.2.0
- libtasn1=4.19.0
- libtiff=4.5.1
- libunistring=0.9.10
- libwebp-base=1.3.2
- lightning=2.3.3
- lightning-utilities=0.11.7
- lz4-c=1.9.4
- markupsafe=2.1.3
- matplotlib-inline=0.1.7
- mkl=2023.1.0
- mkl-service=2.4.0
- mkl_fft=1.3.8
- mkl_random=1.2.4
- mpc=1.1.0
- mpfr=4.0.2
- mpmath=1.3.0
- ncurses=6.4
- nest-asyncio=1.6.0
- nettle=3.7.3
- networkx=3.1
- numpy=1.24.3
- numpy-base=1.24.3
- openh264=2.1.1
- openjpeg=2.5.2
- openssl=3.0.16
- packaging=24.1
- parso=0.8.4
- pexpect=4.9.0
- pickleshare=0.7.5
- pillow=10.4.0
- pip=24.2
- platformdirs=4.3.6
- prompt-toolkit=3.0.43
- ptyprocess=0.7.0
- pygments=2.18.0
- pysocks=1.7.1
- python=3.8.20
- python_abi=3.8
- pytorch=2.0.1
- pytorch-cuda=11.7
- pytorch-lightning=2.3.3
- pytorch-mutex=1.0
- pyzmq=19.0.2
- readline=8.2
- requests=2.32.3
- setuptools=75.1.0
- six=1.16.0
- sqlite=3.45.3
- sympy=1.13.2
- tbb=2021.8.0
- tk=8.6.14
- torchaudio=2.0.2
- torchmetrics=1.4.2
- torchtriton=2.0.0
- torchvision=0.15.2
- tornado=6.1
- tqdm=4.66.5
- traitlets=5.14.3
- typing-extensions=4.11.0
- typing_extensions=4.11.0
- urllib3=2.2.3
- wcwidth=0.2.13
- wheel=0.44.0
- xz=5.4.6
- yaml=0.2.5
- zeromq=4.3.5
- zlib=1.2.13
- zstd=1.5.6
- pip:
  - aiohappyeyeballs==2.4.4
  - aiohttp==3.10.11
  - aiosignal==1.3.1
  - async-timeout==5.0.1
  - attrs==25.3.0
  - clarabel==0.9.0
  - click==8.1.7
  - cloudpickle==3.1.0
  - contourpy==1.1.1
  - cvxpy==1.5.2
  - cycler==0.12.1
  - dask==2023.5.0
  - docker-pycreds==0.4.0
  - ecos==2.0.14
  - einops==0.8.0
  - et-xmlfile==1.1.0
  - fonttools==4.54.1
  - frozenlist==1.5.0
  - gitdb==4.0.11
  - gitpython==3.1.43
  - h5py==3.11.0
  - importlib-metadata==8.5.0
  - importlib-resources==6.4.5
  - kiwisolver==1.4.7
  - kornia==0.7.3
  - kornia-rs==0.1.5
  - locket==1.0.0
  - matplotlib==3.7.5
  - multidict==6.1.0
  - opencv-python==4.10.0.84
  - openpyxl==3.1.5
  - osqp==0.6.7.post3
  - pandas==2.0.3
  - partd==1.4.1
  - plotly==5.24.1
  - portalocker==2.10.1
  - propcache==0.2.0
  - protobuf==5.28.2
  - psutil==6.0.0
  - pyceres==2.3
  - pycolmap==3.10.0
  - pyhocon==0.3.61
  - pyparsing==3.1.4
  - python-dateutil==2.9.0.post0
  - pytz==2024.2
  - pyunionfind==1.0.0
  - pyyaml==6.0.2
  - qdldl==0.1.7.post4
  - scipy==1.10.1
  - scs==3.2.7
  - sentry-sdk==2.16.0
  - setproctitle==1.3.3
  - smmap==5.0.1
  - tenacity==9.0.0
  - toolz==1.0.0
  - torch-geometric==2.6.1
  - torch-scatter==2.1.2
  - tzdata==2024.2
  - wandb==0.18.3
  - yarl==1.15.2
  - zipp==3.20.2
name: RESFM_github
